services:
  orderprocessor:
    build:
      context: ./apps/OrderProcessor
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

  marketdata:
    build:
      context: ./apps/MarketData
      dockerfile: Dockerfile
    ports:
      - "12000:12000"
    restart: always

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - orderprocessor
      - marketdata
