services:
  api:
    build:
      context: ./apps
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    restart: always

  marketdata:
    build:
      context: ./apps/MarketData
      dockerfile: Dockerfile
    ports:
      - "12000:12000"
    restart: always

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - api
      - marketdata
