name: Code Formatter Check

on:
  push:
    branches:
      - "**" # Runs on every branch
  pull_request:
    branches:
      - "**" # Runs on every PR, regardless of the branch

jobs:
  format-check:
    name: Check & Fix Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Prettier & ESLint
        run: npm install -g prettier eslint

      - name: Run Prettier Check
        run: prettier --check "**/*"

      - name: Run ESLint Check
        run: eslint . --ext .js,.ts

      - name: Auto-fix Formatting
        if: github.event_name == 'push'
        run: |
          prettier --write "**/*"
          eslint . --ext .js,.ts --fix
          find . -name "*.java" -print0 | xargs -0 java -jar google-java-format-1.17.0-all-deps.jar -i
          black .

      - name: Commit Changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Auto-format code" || echo "No changes to commit"
          git push || echo "No changes to push"
